# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='studentgroup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='calendarapp.StudentGroup'),
        ),
    ]
