# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_verbose_name_plural_for_calendar'),
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='calendar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.Calendar'),
        ),
    ]
