# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='end',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='start',
            field=models.CharField(max_length=50),
        ),
    ]
