# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_studentgroup_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='calendar',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='acro',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
