# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20170922_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='password',
            field=models.CharField(default='Undefined', max_length=500),
        ),
    ]
