# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20170922_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='start',
            field=models.CharField(max_length=30),
        ),
    ]
