# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-22 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20170922_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
