# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_evaluation_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='course',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
